### ISSUE TITLE
ta certo isso?

### ISSUE THREAD

**Issue by gabrielmancini** [bc-fullstack-01/Raphael-Carvalho-Backend#1]
https://github.com/bc-fullstack-01/Raphael-Carvalho-Backend/blob/966308c9739af4ded3680b134a915e1030725efd/package.json#L10

**Comment by RaphaCarvalh** [comment]
vou analisar, mas aparentemente  não..rs

**Comment by RaphaCarvalh** [comment]
corrigido obrigado!!
